"""Built-in settings grouped by the capability that owns their semantics."""

from .causal_audit import CAUSAL_AUDIT_DEFINITIONS
from .evaluation import EVALUATION_ONTOLOGY_DEFINITIONS
from .general import GENERAL_OPERATIONAL_DEFINITIONS
from .governance import GOVERNANCE_DEFINITIONS
from .operations import OPERATIONS_DEFINITIONS
from .runtime_findings import RUNTIME_FINDINGS_DEFINITIONS
from .telemetry import TELEMETRY_DEFINITIONS

OSS_SETTING_DEFINITION_SETS = (
    GENERAL_OPERATIONAL_DEFINITIONS,
    GOVERNANCE_DEFINITIONS,
    EVALUATION_ONTOLOGY_DEFINITIONS,
    OPERATIONS_DEFINITIONS,
    TELEMETRY_DEFINITIONS,
    RUNTIME_FINDINGS_DEFINITIONS,
    CAUSAL_AUDIT_DEFINITIONS,
)

__all__ = ["OSS_SETTING_DEFINITION_SETS"]
