from __future__ import annotations

from ai_governance.version import __version__

from .common import (
    Category as C,
)
from .common import (
    ValueType as T,
)
from .common import (
    definition as _definition,
)
from .common import (
    non_empty as _non_empty,
)
from .common import (
    range_validator as _range,
)

GENERAL_OPERATIONAL_DEFINITIONS = (
    _definition(
        "general.instance_name",
        C.GENERAL,
        "Instance Name",
        "Human-readable AI Governance Control Plane instance name.",
        T.STRING,
        "AI Governance Control Plane",
        env="AI_GOVERNANCE_INSTANCE_NAME",
        validator=_non_empty,
        runtime_applied=True,
    ),
    _definition(
        "general.environment",
        C.GENERAL,
        "Environment",
        "Deployment environment.",
        T.ENUM,
        "local",
        mutable=False,
        env="AI_GOVERNANCE_ENV",
        restart=True,
        enum=("local", "development", "staging", "production"),
    ),
    _definition(
        "general.version",
        C.GENERAL,
        "Version",
        "Installed AI Governance Control Plane release.",
        T.STRING,
        __version__,
        mutable=False,
    ),
    _definition(
        "general.build",
        C.GENERAL,
        "Build",
        "Build identifier.",
        T.STRING,
        "development",
        mutable=False,
        env="AI_GOVERNANCE_BUILD_ID",
        restart=True,
    ),
    _definition(
        "general.timezone",
        C.GENERAL,
        "Timezone",
        "Display timezone.",
        T.STRING,
        "UTC",
        env="AI_GOVERNANCE_TIMEZONE",
        validator=_non_empty,
        runtime_applied=True,
    ),
    _definition(
        "repositories.active_backend",
        C.REPOSITORIES,
        "Active Backend",
        "Primary repository backend.",
        T.ENUM,
        "inmemory",
        mutable=False,
        env="AI_GOVERNANCE_POLICY_REPOSITORY",
        restart=True,
        enum=("inmemory", "sqlite", "postgres"),
    ),
    _definition(
        "repositories.settings_backend",
        C.REPOSITORIES,
        "Settings Backend",
        "Runtime settings repository backend.",
        T.ENUM,
        "inmemory",
        mutable=False,
        env="AI_GOVERNANCE_SETTINGS_REPOSITORY",
        restart=True,
        enum=("inmemory", "sqlite", "postgres"),
    ),
    _definition(
        "repositories.connection_status",
        C.REPOSITORIES,
        "Connection Status",
        "Settings repository connection status.",
        T.ENUM,
        "connected",
        mutable=False,
        enum=("connected", "disconnected"),
    ),
    _definition(
        "repositories.migration_status",
        C.REPOSITORIES,
        "Migration Status",
        "Database migration status.",
        T.ENUM,
        "current",
        mutable=False,
        enum=("current", "pending", "unknown"),
    ),
    _definition(
        "jobs.worker_concurrency",
        C.JOBS,
        "Worker Concurrency",
        "Maximum concurrent job workers.",
        T.INTEGER,
        4,
        env="AI_GOVERNANCE_JOB_WORKER_CONCURRENCY",
        validator=_range(1, 128),
        runtime_applied=True,
    ),
    _definition(
        "jobs.retry_attempts",
        C.JOBS,
        "Retry Attempts",
        "Default job retry attempts.",
        T.INTEGER,
        3,
        env="AI_GOVERNANCE_JOB_RETRY_ATTEMPTS",
        validator=_range(1, 10),
        runtime_applied=True,
    ),
    _definition(
        "jobs.retry_delay",
        C.JOBS,
        "Retry Delay",
        "Delay between job retries.",
        T.DURATION,
        "1ms",
        env="AI_GOVERNANCE_JOB_RETRY_DELAY",
        runtime_applied=True,
    ),
    _definition(
        "jobs.queue_size",
        C.JOBS,
        "Queue Size",
        "Maximum queued jobs.",
        T.INTEGER,
        1000,
        env="AI_GOVERNANCE_JOB_QUEUE_SIZE",
        validator=_range(1, 100000),
        runtime_applied=True,
    ),
    _definition(
        "jobs.retention",
        C.JOBS,
        "Retention",
        "Completed-job retention period.",
        T.DURATION,
        "30d",
        env="AI_GOVERNANCE_JOB_RETENTION",
        runtime_applied=True,
    ),

)
