from __future__ import annotations

from .common import (
    Category as C,
    ValueType as T,
    definition as _definition,
    non_empty as _non_empty,
    range_validator as _range,
    synthesizer_pricing as _synthesizer_pricing,
)

GOVERNANCE_DEFINITIONS = (
    _definition(
        "governance.decision_retention",
        C.GOVERNANCE,
        "Decision Retention",
        "Governance decision retention period.",
        T.DURATION,
        "365d",
        env="AI_GOVERNANCE_DECISION_RETENTION",
        runtime_applied=True,
    ),
    _definition(
        "governance.replay_retention",
        C.GOVERNANCE,
        "Replay Retention",
        "Workflow replay retention period.",
        T.DURATION,
        "90d",
        env="AI_GOVERNANCE_REPLAY_RETENTION",
        runtime_applied=True,
    ),
    _definition(
        "replay.retention",
        C.GOVERNANCE,
        "Replay Retention",
        "Retention period for archived Replay Management records.",
        T.DURATION,
        "90d",
        env="AI_GOVERNANCE_REPLAY_RETENTION",
        runtime_applied=True,
    ),
    _definition(
        "replay.max_concurrent_jobs",
        C.GOVERNANCE,
        "Replay Maximum Concurrent Jobs",
        "Maximum replay execution jobs across the platform.",
        T.INTEGER,
        4,
        env="AI_GOVERNANCE_REPLAY_MAX_CONCURRENT_JOBS",
        validator=_range(1, 128),
        runtime_applied=True,
    ),
    _definition(
        "replay.max_concurrent_jobs_per_project",
        C.GOVERNANCE,
        "Replay Maximum Concurrent Jobs Per Project",
        "Maximum replay execution jobs within one project.",
        T.INTEGER,
        2,
        env="AI_GOVERNANCE_REPLAY_MAX_CONCURRENT_JOBS_PER_PROJECT",
        validator=_range(1, 128),
        runtime_applied=True,
    ),
    _definition(
        "replay.max_attempts",
        C.GOVERNANCE,
        "Replay Maximum Attempts",
        "Maximum job attempts for one replay execution.",
        T.INTEGER,
        3,
        env="AI_GOVERNANCE_REPLAY_MAX_ATTEMPTS",
        validator=_range(1, 10),
        runtime_applied=True,
    ),
    _definition(
        "replay.default_baseline_strategy",
        C.GOVERNANCE,
        "Replay Default Baseline Strategy",
        "Baseline strategy used for replay evaluation when none is specified.",
        T.ENUM,
        "LATEST_COMPATIBLE",
        env="AI_GOVERNANCE_REPLAY_DEFAULT_BASELINE_STRATEGY",
        enum=("EXPLICIT", "LATEST_COMPATIBLE", "SOURCE_PRIMARY"),
        runtime_applied=True,
    ),
    _definition(
        "replay.evaluation_max_attempts",
        C.GOVERNANCE,
        "Replay Evaluation Maximum Attempts",
        "Maximum attempts for a replay evaluation job.",
        T.INTEGER,
        3,
        env="AI_GOVERNANCE_REPLAY_EVALUATION_MAX_ATTEMPTS",
        validator=_range(1, 10),
        runtime_applied=True,
    ),
    _definition(
        "replay.drift_threshold_policy",
        C.GOVERNANCE,
        "Replay Drift Threshold Policy",
        "Resolved drift policy retained with replay evidence.",
        T.JSON,
        {"policy": "governance-default-v1"},
        env="AI_GOVERNANCE_REPLAY_DRIFT_THRESHOLD_POLICY",
        runtime_applied=True,
    ),
    _definition(
        "replay.result_retention",
        C.GOVERNANCE,
        "Replay Result Retention",
        "Retention period for immutable replay result evidence.",
        T.DURATION,
        "90d",
        env="AI_GOVERNANCE_REPLAY_RESULT_RETENTION",
        runtime_applied=True,
    ),
    _definition(
        "intelligence.replay_history_limit",
        C.GOVERNANCE,
        "Replay Advisor Historical Job Limit",
        "Maximum terminal Replay jobs supplied to the Intelligence Replay Advisor.",
        T.INTEGER,
        3,
        env="AI_GOVERNANCE_INTELLIGENCE_REPLAY_HISTORY_LIMIT",
        validator=_range(1, 20),
        runtime_applied=True,
    ),
    _definition(
        "intelligence.synthesizer_provider",
        C.GOVERNANCE,
        "Intelligence Synthesizer Provider",
        "Configured governed provider used to synthesize Intelligence evidence.",
        T.STRING,
        "openai",
        env="AI_GOVERNANCE_INTELLIGENCE_SYNTHESIZER_PROVIDER",
        validator=_non_empty,
        runtime_applied=True,
    ),
    _definition(
        "intelligence.synthesizer_model",
        C.GOVERNANCE,
        "Intelligence Synthesizer Model",
        "Model selected for evidence-grounded Intelligence synthesis.",
        T.STRING,
        "gpt-4.1-mini",
        env="AI_GOVERNANCE_INTELLIGENCE_SYNTHESIZER_MODEL",
        validator=_non_empty,
        runtime_applied=True,
    ),
    _definition(
        "intelligence.synthesizer_pricing",
        C.GOVERNANCE,
        "Intelligence Synthesizer Pricing",
        "Estimated USD rates per million tokens for each Intelligence synthesis model.",
        T.JSON,
        {
            "gpt-4.1-mini": {"input": 0.40, "cached_input": 0.10, "output": 1.60},
            "gpt-5.6-luna": {"input": 1.00, "cached_input": 0.10, "output": 6.00},
            "gpt-5.6-terra": {"input": 2.50, "cached_input": 0.25, "output": 15.00},
            "gpt-5.6-sol": {"input": 5.00, "cached_input": 0.50, "output": 30.00},
        },
        env="AI_GOVERNANCE_INTELLIGENCE_SYNTHESIZER_PRICING",
        validator=_synthesizer_pricing,
        runtime_applied=True,
    ),
    _definition(
        "enterprise.recommendations.enabled",
        C.GOVERNANCE,
        "Enterprise Recommendations Enabled",
        "Enable read-only Enterprise recommendation collection.",
        T.BOOLEAN,
        True,
        env="AI_GOVERNANCE_ENTERPRISE_RECOMMENDATIONS_ENABLED",
        runtime_applied=True,
    ),
    _definition(
        "enterprise.recommendations.default_limit",
        C.GOVERNANCE,
        "Enterprise Recommendations Default Limit",
        "Default maximum number of recommendations returned.",
        T.INTEGER,
        20,
        validator=_range(1, 100),
        runtime_applied=True,
    ),
    _definition(
        "enterprise.recommendations.include_informational",
        C.GOVERNANCE,
        "Enterprise Recommendations Include Informational",
        "Include informational recommendations by default.",
        T.BOOLEAN,
        False,
        runtime_applied=True,
    ),
    _definition(
        "enterprise.recommendations.narrative_enabled",
        C.GOVERNANCE,
        "Enterprise Recommendation Narrative Enabled",
        "Permit provider-backed wording after deterministic recommendation collection.",
        T.BOOLEAN,
        False,
        runtime_applied=True,
    ),
    _definition(
        "enterprise.recommendations.max_narrative_items",
        C.GOVERNANCE,
        "Enterprise Recommendation Narrative Limit",
        "Maximum recommendations eligible for narrative synthesis per request.",
        T.INTEGER,
        5,
        validator=_range(0, 20),
        runtime_applied=True,
    ),
    _definition(
        "enterprise.recommendations.operational_window_days",
        C.GOVERNANCE,
        "Enterprise Operational Summary Window",
        "Default requested operational summary window in days.",
        T.INTEGER,
        7,
        validator=_range(1, 30),
        runtime_applied=True,
    ),
    _definition(
        "enterprise.recommendations.governance_weight",
        C.GOVERNANCE,
        "Governance Recommendation Weight",
        "Deterministic relative priority weight for governance recommendations.",
        T.FLOAT,
        1.0,
        validator=_range(0, 10),
        runtime_applied=True,
    ),
    _definition(
        "enterprise.recommendations.replay_weight",
        C.GOVERNANCE,
        "Replay Recommendation Weight",
        "Deterministic relative priority weight for replay recommendations.",
        T.FLOAT,
        1.0,
        validator=_range(0, 10),
        runtime_applied=True,
    ),
    _definition(
        "enterprise.recommendations.experiment_weight",
        C.GOVERNANCE,
        "Experiment Recommendation Weight",
        "Deterministic relative priority weight for experiment recommendations.",
        T.FLOAT,
        1.0,
        validator=_range(0, 10),
        runtime_applied=True,
    ),
    _definition(
        "enterprise.recommendations.root_cause_weight",
        C.GOVERNANCE,
        "Root-cause Recommendation Weight",
        "Deterministic relative priority weight for root-cause recommendations.",
        T.FLOAT,
        1.0,
        validator=_range(0, 10),
        runtime_applied=True,
    ),
    _definition(
        "enterprise.recommendations.operational_weight",
        C.GOVERNANCE,
        "Operational Recommendation Weight",
        "Deterministic relative priority weight for operational recommendations.",
        T.FLOAT,
        1.0,
        validator=_range(0, 10),
        runtime_applied=True,
    ),
    _definition(
        "governance.default_policy_version_behavior",
        C.GOVERNANCE,
        "Default Policy Version",
        "Policy version selection behavior.",
        T.ENUM,
        "active",
        env="AI_GOVERNANCE_DEFAULT_POLICY_VERSION_BEHAVIOR",
        enum=("active", "latest", "explicit"),
        runtime_applied=True,
    ),

)
