from __future__ import annotations

from ai_governance.domain.models import known_runtime_model_provider_keys
from ai_governance.version import __version__

from .common import (
    Category as C,
)
from .common import (
    ValueType as T,
)
from .common import (
    definition as _definition,
)
from .common import (
    runtime_model_provider_allow_list as _runtime_model_provider_allow_list,
)

OPERATIONS_DEFINITIONS = (
    _definition(
        "audit.retention",
        C.AUDIT,
        "Retention",
        "Audit record retention period.",
        T.DURATION,
        "365d",
        env="AI_GOVERNANCE_AUDIT_RETENTION",
        runtime_applied=True,
    ),
    _definition(
        "audit.interrupted_timeout",
        C.AUDIT,
        "Interrupted Timeout",
        "Timeout before an operation is considered interrupted.",
        T.DURATION,
        "15m",
        env="AI_GOVERNANCE_AUDIT_INTERRUPTED_TIMEOUT",
        runtime_applied=True,
    ),
    _definition(
        "audit.backend",
        C.AUDIT,
        "Backend",
        "Audit persistence backend.",
        T.ENUM,
        "sqlite",
        mutable=False,
        env="AI_GOVERNANCE_MCP_AUDIT_BACKEND",
        restart=True,
        enum=("memory", "sqlite", "postgres"),
    ),
    _definition(
        "mcp.dry_run_default",
        C.MCP,
        "Dry-run Default",
        "Default MCP controlled writes to dry-run.",
        T.BOOLEAN,
        False,
        env="AI_GOVERNANCE_MCP_DRY_RUN_DEFAULT",
        runtime_applied=True,
    ),
    _definition(
        "mcp.audit_required",
        C.MCP,
        "Audit Required",
        "Require audit logging for MCP writes.",
        T.BOOLEAN,
        True,
        env="AI_GOVERNANCE_MCP_AUDIT_REQUIRED",
        runtime_applied=True,
    ),
    _definition(
        "mcp.idempotency_expiry",
        C.MCP,
        "Idempotency Expiry",
        "MCP idempotency-key retention.",
        T.DURATION,
        "24h",
        env="AI_GOVERNANCE_MCP_IDEMPOTENCY_EXPIRY",
        runtime_applied=True,
    ),
    _definition(
        "integrations.openai",
        C.INTEGRATIONS,
        "OpenAI",
        "OpenAI integration status.",
        T.ENUM,
        "disconnected",
        mutable=False,
        env="OPENAI_API_KEY",
        enum=("connected", "disconnected"),
        sensitive=True,
    ),
    _definition(
        "model_registry.allowed_runtime_providers",
        C.INTEGRATIONS,
        "Allowed Managed Model Runtime Providers",
        "Runtime providers permitted when registering managed models. "
        "Observed runtime evidence is retained even when its provider is not listed.",
        T.JSON,
        list(known_runtime_model_provider_keys()),
        validator=_runtime_model_provider_allow_list,
        runtime_applied=True,
    ),
    _definition(
        "integrations.neo4j",
        C.INTEGRATIONS,
        "Neo4j",
        "Neo4j integration status.",
        T.ENUM,
        "disconnected",
        mutable=False,
        env="AI_GOVERNANCE_GRAPH_URI",
        enum=("connected", "disconnected"),
    ),
    _definition(
        "integrations.msteams",
        C.INTEGRATIONS,
        "MS Teams",
        "MS Teams integration status.",
        T.ENUM,
        "disconnected",
        mutable=False,
        env="AI_GOVERNANCE_MSTEAMS_WEBHOOK_URL",
        enum=("connected", "disconnected"),
        sensitive=True,
    ),
    _definition(
        "integrations.webhook",
        C.INTEGRATIONS,
        "Webhook",
        "Webhook integration status.",
        T.ENUM,
        "disconnected",
        mutable=False,
        env="AI_GOVERNANCE_WEBHOOK_URL",
        enum=("connected", "disconnected"),
        sensitive=True,
    ),
    _definition(
        "system.version",
        C.SYSTEM,
        "Version",
        "Installed AI Governance Control Plane release.",
        T.STRING,
        __version__,
        mutable=False,
    ),
    _definition(
        "system.commit_sha",
        C.SYSTEM,
        "Commit SHA",
        "Source revision.",
        T.STRING,
        "unknown",
        mutable=False,
        env="AI_GOVERNANCE_COMMIT_SHA",
        restart=True,
    ),
    _definition(
        "system.build_date",
        C.SYSTEM,
        "Build Date",
        "Build timestamp.",
        T.STRING,
        "unknown",
        mutable=False,
        env="AI_GOVERNANCE_BUILD_DATE",
        restart=True,
    ),
    _definition(
        "system.python_version",
        C.SYSTEM,
        "Python Version",
        "Python runtime version.",
        T.STRING,
        "runtime",
        mutable=False,
    ),

)
