"""Runtime findings detector configuration settings.

All detector thresholds, sample sizes, and time windows are externalized
through the settings control plane. Changing detection behaviour requires
only a settings update — no code changes.
"""

from __future__ import annotations

from ai_governance.settings_control.domain import SettingScope

from .common import (
    Category as C,
)
from .common import (
    ValueType as T,
)
from .common import (
    definition as _definition,
)
from .common import (
    range_validator,
)

RUNTIME_FINDINGS_DEFINITIONS = (
    # -----------------------------------------------------------------------
    # Tool failure rate detector
    # -----------------------------------------------------------------------
    _definition(
        "runtime_findings.tool_failure_rate.min_observation_count",
        C.AGENTS_RUNTIME,
        "Tool Failure Rate — Min Observations",
        "Minimum tool-call observations before the detector fires. "
        "Prevents findings from tiny sample sizes.",
        T.INTEGER,
        30,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_TOOL_FAILURE_MIN_OBSERVATIONS",
        runtime_applied=True,
        validator=range_validator(1, 10000),
    ),
    _definition(
        "runtime_findings.tool_failure_rate.baseline_window_days",
        C.AGENTS_RUNTIME,
        "Tool Failure Rate — Baseline Window (days)",
        "Number of days for the historical baseline window.",
        T.INTEGER,
        7,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_TOOL_FAILURE_BASELINE_DAYS",
        runtime_applied=True,
        validator=range_validator(1, 365),
    ),
    _definition(
        "runtime_findings.tool_failure_rate.observation_window_hours",
        C.AGENTS_RUNTIME,
        "Tool Failure Rate — Observation Window (hours)",
        "Number of hours for the current observation window.",
        T.INTEGER,
        24,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_TOOL_FAILURE_OBSERVATION_HOURS",
        runtime_applied=True,
        validator=range_validator(1, 720),
    ),
    _definition(
        "runtime_findings.tool_failure_rate.absolute_threshold",
        C.AGENTS_RUNTIME,
        "Tool Failure Rate — Absolute Threshold",
        "Minimum observed failure rate (0.0–1.0) to trigger a finding.",
        T.FLOAT,
        0.05,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_TOOL_FAILURE_ABSOLUTE_THRESHOLD",
        runtime_applied=True,
        validator=range_validator(0.0, 1.0),
    ),
    _definition(
        "runtime_findings.tool_failure_rate.relative_threshold",
        C.AGENTS_RUNTIME,
        "Tool Failure Rate — Relative Threshold",
        "Minimum multiplicative increase over baseline (e.g. 2.0 = 2x).",
        T.FLOAT,
        2.0,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_TOOL_FAILURE_RELATIVE_THRESHOLD",
        runtime_applied=True,
        validator=range_validator(1.0, 100.0),
    ),
    _definition(
        "runtime_findings.tool_failure_rate.severity_critical_threshold",
        C.AGENTS_RUNTIME,
        "Tool Failure Rate — Critical Severity Threshold",
        "Failure rate at or above this value produces CRITICAL severity.",
        T.FLOAT,
        0.25,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_TOOL_FAILURE_SEVERITY_CRITICAL",
        runtime_applied=True,
        validator=range_validator(0.0, 1.0),
    ),
    _definition(
        "runtime_findings.tool_failure_rate.severity_high_threshold",
        C.AGENTS_RUNTIME,
        "Tool Failure Rate — High Severity Threshold",
        "Failure rate at or above this value produces HIGH severity.",
        T.FLOAT,
        0.15,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_TOOL_FAILURE_SEVERITY_HIGH",
        runtime_applied=True,
        validator=range_validator(0.0, 1.0),
    ),
    _definition(
        "runtime_findings.tool_failure_rate.severity_medium_threshold",
        C.AGENTS_RUNTIME,
        "Tool Failure Rate — Medium Severity Threshold",
        "Failure rate at or above this value produces MEDIUM severity.",
        T.FLOAT,
        0.10,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_TOOL_FAILURE_SEVERITY_MEDIUM",
        runtime_applied=True,
        validator=range_validator(0.0, 1.0),
    ),
    _definition(
        "runtime_findings.tool_failure_rate.severity_low_threshold",
        C.AGENTS_RUNTIME,
        "Tool Failure Rate — Low Severity Threshold",
        "Failure rate at or above this value produces LOW severity.",
        T.FLOAT,
        0.05,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_TOOL_FAILURE_SEVERITY_LOW",
        runtime_applied=True,
        validator=range_validator(0.0, 1.0),
    ),
    _definition(
        "runtime_findings.tool_failure_rate.resolution_window_hours",
        C.AGENTS_RUNTIME,
        "Tool Failure Rate — Resolution Window (hours)",
        "Hours of normal metrics before auto-resolution.",
        T.INTEGER,
        48,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_TOOL_FAILURE_RESOLUTION_HOURS",
        runtime_applied=True,
        validator=range_validator(1, 720),
    ),

    # -----------------------------------------------------------------------
    # Agent execution failure rate detector
    # -----------------------------------------------------------------------
    _definition(
        "runtime_findings.agent_execution_failure_rate.min_observation_count",
        C.AGENTS_RUNTIME,
        "Agent Execution Failure Rate — Min Observations",
        "Minimum execution observations before the detector fires.",
        T.INTEGER,
        20,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_AGENT_EXEC_FAILURE_MIN_OBSERVATIONS",
        runtime_applied=True,
        validator=range_validator(1, 10000),
    ),
    _definition(
        "runtime_findings.agent_execution_failure_rate.baseline_window_days",
        C.AGENTS_RUNTIME,
        "Agent Execution Failure Rate — Baseline Window (days)",
        "Number of days for the historical baseline window.",
        T.INTEGER,
        7,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_AGENT_EXEC_FAILURE_BASELINE_DAYS",
        runtime_applied=True,
        validator=range_validator(1, 365),
    ),
    _definition(
        "runtime_findings.agent_execution_failure_rate.observation_window_hours",
        C.AGENTS_RUNTIME,
        "Agent Execution Failure Rate — Observation Window (hours)",
        "Number of hours for the current observation window.",
        T.INTEGER,
        24,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_AGENT_EXEC_FAILURE_OBSERVATION_HOURS",
        runtime_applied=True,
        validator=range_validator(1, 720),
    ),
    _definition(
        "runtime_findings.agent_execution_failure_rate.absolute_threshold",
        C.AGENTS_RUNTIME,
        "Agent Execution Failure Rate — Absolute Threshold",
        "Minimum observed failure rate (0.0–1.0) to trigger a finding.",
        T.FLOAT,
        0.10,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_AGENT_EXEC_FAILURE_ABSOLUTE_THRESHOLD",
        runtime_applied=True,
        validator=range_validator(0.0, 1.0),
    ),
    _definition(
        "runtime_findings.agent_execution_failure_rate.relative_threshold",
        C.AGENTS_RUNTIME,
        "Agent Execution Failure Rate — Relative Threshold",
        "Minimum multiplicative increase over baseline (e.g. 2.0 = 2x).",
        T.FLOAT,
        2.0,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_AGENT_EXEC_FAILURE_RELATIVE_THRESHOLD",
        runtime_applied=True,
        validator=range_validator(1.0, 100.0),
    ),
    _definition(
        "runtime_findings.agent_execution_failure_rate.severity_critical_threshold",
        C.AGENTS_RUNTIME,
        "Agent Execution Failure Rate — Critical Severity Threshold",
        "Failure rate at or above this value produces CRITICAL severity.",
        T.FLOAT,
        0.50,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_AGENT_EXEC_FAILURE_SEVERITY_CRITICAL",
        runtime_applied=True,
        validator=range_validator(0.0, 1.0),
    ),
    _definition(
        "runtime_findings.agent_execution_failure_rate.severity_high_threshold",
        C.AGENTS_RUNTIME,
        "Agent Execution Failure Rate — High Severity Threshold",
        "Failure rate at or above this value produces HIGH severity.",
        T.FLOAT,
        0.30,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_AGENT_EXEC_FAILURE_SEVERITY_HIGH",
        runtime_applied=True,
        validator=range_validator(0.0, 1.0),
    ),
    _definition(
        "runtime_findings.agent_execution_failure_rate.severity_medium_threshold",
        C.AGENTS_RUNTIME,
        "Agent Execution Failure Rate — Medium Severity Threshold",
        "Failure rate at or above this value produces MEDIUM severity.",
        T.FLOAT,
        0.20,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_AGENT_EXEC_FAILURE_SEVERITY_MEDIUM",
        runtime_applied=True,
        validator=range_validator(0.0, 1.0),
    ),
    _definition(
        "runtime_findings.agent_execution_failure_rate.severity_low_threshold",
        C.AGENTS_RUNTIME,
        "Agent Execution Failure Rate — Low Severity Threshold",
        "Failure rate at or above this value produces LOW severity.",
        T.FLOAT,
        0.10,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_AGENT_EXEC_FAILURE_SEVERITY_LOW",
        runtime_applied=True,
        validator=range_validator(0.0, 1.0),
    ),
    _definition(
        "runtime_findings.agent_execution_failure_rate.resolution_window_hours",
        C.AGENTS_RUNTIME,
        "Agent Execution Failure Rate — Resolution Window (hours)",
        "Hours of normal metrics before auto-resolution.",
        T.INTEGER,
        48,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_AGENT_EXEC_FAILURE_RESOLUTION_HOURS",
        runtime_applied=True,
        validator=range_validator(1, 720),
    ),

    # -----------------------------------------------------------------------
    # Execution latency regression detector
    # -----------------------------------------------------------------------
    _definition(
        "runtime_findings.execution_latency_regression.min_observation_count",
        C.AGENTS_RUNTIME,
        "Execution Latency Regression — Min Observations",
        "Minimum execution observations before the detector fires.",
        T.INTEGER,
        20,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_LATENCY_MIN_OBSERVATIONS",
        runtime_applied=True,
        validator=range_validator(1, 10000),
    ),
    _definition(
        "runtime_findings.execution_latency_regression.baseline_window_days",
        C.AGENTS_RUNTIME,
        "Execution Latency Regression — Baseline Window (days)",
        "Number of days for the historical baseline window.",
        T.INTEGER,
        7,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_LATENCY_BASELINE_DAYS",
        runtime_applied=True,
        validator=range_validator(1, 365),
    ),
    _definition(
        "runtime_findings.execution_latency_regression.observation_window_hours",
        C.AGENTS_RUNTIME,
        "Execution Latency Regression — Observation Window (hours)",
        "Number of hours for the current observation window.",
        T.INTEGER,
        24,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_LATENCY_OBSERVATION_HOURS",
        runtime_applied=True,
        validator=range_validator(1, 720),
    ),
    _definition(
        "runtime_findings.execution_latency_regression.relative_threshold",
        C.AGENTS_RUNTIME,
        "Execution Latency Regression — Relative Threshold",
        "Minimum multiplicative increase in median duration.",
        T.FLOAT,
        1.5,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_LATENCY_RELATIVE_THRESHOLD",
        runtime_applied=True,
        validator=range_validator(1.0, 100.0),
    ),
    _definition(
        "runtime_findings.execution_latency_regression.severity_critical_threshold",
        C.AGENTS_RUNTIME,
        "Execution Latency Regression — Critical Severity Threshold",
        "Latency ratio at or above this value produces CRITICAL severity.",
        T.FLOAT,
        3.0,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_LATENCY_SEVERITY_CRITICAL",
        runtime_applied=True,
        validator=range_validator(1.0, 100.0),
    ),
    _definition(
        "runtime_findings.execution_latency_regression.severity_high_threshold",
        C.AGENTS_RUNTIME,
        "Execution Latency Regression — High Severity Threshold",
        "Latency ratio at or above this value produces HIGH severity.",
        T.FLOAT,
        2.0,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_LATENCY_SEVERITY_HIGH",
        runtime_applied=True,
        validator=range_validator(1.0, 100.0),
    ),
    _definition(
        "runtime_findings.execution_latency_regression.severity_medium_threshold",
        C.AGENTS_RUNTIME,
        "Execution Latency Regression — Medium Severity Threshold",
        "Latency ratio at or above this value produces MEDIUM severity.",
        T.FLOAT,
        1.5,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_LATENCY_SEVERITY_MEDIUM",
        runtime_applied=True,
        validator=range_validator(1.0, 100.0),
    ),
    _definition(
        "runtime_findings.execution_latency_regression.severity_low_threshold",
        C.AGENTS_RUNTIME,
        "Execution Latency Regression — Low Severity Threshold",
        "Latency ratio at or above this value produces LOW severity.",
        T.FLOAT,
        1.2,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_LATENCY_SEVERITY_LOW",
        runtime_applied=True,
        validator=range_validator(1.0, 100.0),
    ),
    _definition(
        "runtime_findings.execution_latency_regression.resolution_window_hours",
        C.AGENTS_RUNTIME,
        "Execution Latency Regression — Resolution Window (hours)",
        "Hours of normal latency before auto-resolution.",
        T.INTEGER,
        48,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_LATENCY_RESOLUTION_HOURS",
        runtime_applied=True,
        validator=range_validator(1, 720),
    ),

    # -----------------------------------------------------------------------
    # Evaluation failure rate detector
    # -----------------------------------------------------------------------
    _definition(
        "runtime_findings.evaluation_failure_rate.min_observation_count",
        C.AGENTS_RUNTIME,
        "Evaluation Failure Rate — Min Observations",
        "Minimum evaluation observations before the detector fires.",
        T.INTEGER,
        10,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_EVAL_FAILURE_MIN_OBSERVATIONS",
        runtime_applied=True,
        validator=range_validator(1, 10000),
    ),
    _definition(
        "runtime_findings.evaluation_failure_rate.baseline_window_days",
        C.AGENTS_RUNTIME,
        "Evaluation Failure Rate — Baseline Window (days)",
        "Number of days for the historical baseline window.",
        T.INTEGER,
        7,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_EVAL_FAILURE_BASELINE_DAYS",
        runtime_applied=True,
        validator=range_validator(1, 365),
    ),
    _definition(
        "runtime_findings.evaluation_failure_rate.observation_window_hours",
        C.AGENTS_RUNTIME,
        "Evaluation Failure Rate — Observation Window (hours)",
        "Number of hours for the current observation window.",
        T.INTEGER,
        24,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_EVAL_FAILURE_OBSERVATION_HOURS",
        runtime_applied=True,
        validator=range_validator(1, 720),
    ),
    _definition(
        "runtime_findings.evaluation_failure_rate.absolute_threshold",
        C.AGENTS_RUNTIME,
        "Evaluation Failure Rate — Absolute Threshold",
        "Minimum observed failure rate (0.0–1.0) to trigger a finding.",
        T.FLOAT,
        0.15,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_EVAL_FAILURE_ABSOLUTE_THRESHOLD",
        runtime_applied=True,
        validator=range_validator(0.0, 1.0),
    ),
    _definition(
        "runtime_findings.evaluation_failure_rate.relative_threshold",
        C.AGENTS_RUNTIME,
        "Evaluation Failure Rate — Relative Threshold",
        "Minimum multiplicative increase over baseline (e.g. 2.0 = 2x).",
        T.FLOAT,
        2.0,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_EVAL_FAILURE_RELATIVE_THRESHOLD",
        runtime_applied=True,
        validator=range_validator(1.0, 100.0),
    ),
    _definition(
        "runtime_findings.evaluation_failure_rate.severity_critical_threshold",
        C.AGENTS_RUNTIME,
        "Evaluation Failure Rate — Critical Severity Threshold",
        "Failure rate at or above this value produces CRITICAL severity.",
        T.FLOAT,
        0.50,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_EVAL_FAILURE_SEVERITY_CRITICAL",
        runtime_applied=True,
        validator=range_validator(0.0, 1.0),
    ),
    _definition(
        "runtime_findings.evaluation_failure_rate.severity_high_threshold",
        C.AGENTS_RUNTIME,
        "Evaluation Failure Rate — High Severity Threshold",
        "Failure rate at or above this value produces HIGH severity.",
        T.FLOAT,
        0.30,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_EVAL_FAILURE_SEVERITY_HIGH",
        runtime_applied=True,
        validator=range_validator(0.0, 1.0),
    ),
    _definition(
        "runtime_findings.evaluation_failure_rate.severity_medium_threshold",
        C.AGENTS_RUNTIME,
        "Evaluation Failure Rate — Medium Severity Threshold",
        "Failure rate at or above this value produces MEDIUM severity.",
        T.FLOAT,
        0.20,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_EVAL_FAILURE_SEVERITY_MEDIUM",
        runtime_applied=True,
        validator=range_validator(0.0, 1.0),
    ),
    _definition(
        "runtime_findings.evaluation_failure_rate.severity_low_threshold",
        C.AGENTS_RUNTIME,
        "Evaluation Failure Rate — Low Severity Threshold",
        "Failure rate at or above this value produces LOW severity.",
        T.FLOAT,
        0.15,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_EVAL_FAILURE_SEVERITY_LOW",
        runtime_applied=True,
        validator=range_validator(0.0, 1.0),
    ),
    _definition(
        "runtime_findings.evaluation_failure_rate.resolution_window_hours",
        C.AGENTS_RUNTIME,
        "Evaluation Failure Rate — Resolution Window (hours)",
        "Hours of normal metrics before auto-resolution.",
        T.INTEGER,
        48,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_EVAL_FAILURE_RESOLUTION_HOURS",
        runtime_applied=True,
        validator=range_validator(1, 720),
    ),

    # -----------------------------------------------------------------------
    # Policy denial rate detector
    # -----------------------------------------------------------------------
    _definition(
        "runtime_findings.policy_denial_rate.min_observation_count",
        C.AGENTS_RUNTIME,
        "Policy Denial Rate — Min Observations",
        "Minimum governance decision observations before the detector fires.",
        T.INTEGER,
        10,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_POLICY_DENIAL_MIN_OBSERVATIONS",
        runtime_applied=True,
        validator=range_validator(1, 10000),
    ),
    _definition(
        "runtime_findings.policy_denial_rate.baseline_window_days",
        C.AGENTS_RUNTIME,
        "Policy Denial Rate — Baseline Window (days)",
        "Number of days for the historical baseline window.",
        T.INTEGER,
        7,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_POLICY_DENIAL_BASELINE_DAYS",
        runtime_applied=True,
        validator=range_validator(1, 365),
    ),
    _definition(
        "runtime_findings.policy_denial_rate.observation_window_hours",
        C.AGENTS_RUNTIME,
        "Policy Denial Rate — Observation Window (hours)",
        "Number of hours for the current observation window.",
        T.INTEGER,
        24,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_POLICY_DENIAL_OBSERVATION_HOURS",
        runtime_applied=True,
        validator=range_validator(1, 720),
    ),
    _definition(
        "runtime_findings.policy_denial_rate.absolute_threshold",
        C.AGENTS_RUNTIME,
        "Policy Denial Rate — Absolute Threshold",
        "Minimum observed denial rate (0.0–1.0) to trigger a finding.",
        T.FLOAT,
        0.10,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_POLICY_DENIAL_ABSOLUTE_THRESHOLD",
        runtime_applied=True,
        validator=range_validator(0.0, 1.0),
    ),
    _definition(
        "runtime_findings.policy_denial_rate.relative_threshold",
        C.AGENTS_RUNTIME,
        "Policy Denial Rate — Relative Threshold",
        "Minimum multiplicative increase over baseline (e.g. 2.0 = 2x).",
        T.FLOAT,
        2.0,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_POLICY_DENIAL_RELATIVE_THRESHOLD",
        runtime_applied=True,
        validator=range_validator(1.0, 100.0),
    ),
    _definition(
        "runtime_findings.policy_denial_rate.severity_critical_threshold",
        C.AGENTS_RUNTIME,
        "Policy Denial Rate — Critical Severity Threshold",
        "Denial rate at or above this value produces CRITICAL severity.",
        T.FLOAT,
        0.50,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_POLICY_DENIAL_SEVERITY_CRITICAL",
        runtime_applied=True,
        validator=range_validator(0.0, 1.0),
    ),
    _definition(
        "runtime_findings.policy_denial_rate.severity_high_threshold",
        C.AGENTS_RUNTIME,
        "Policy Denial Rate — High Severity Threshold",
        "Denial rate at or above this value produces HIGH severity.",
        T.FLOAT,
        0.30,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_POLICY_DENIAL_SEVERITY_HIGH",
        runtime_applied=True,
        validator=range_validator(0.0, 1.0),
    ),
    _definition(
        "runtime_findings.policy_denial_rate.severity_medium_threshold",
        C.AGENTS_RUNTIME,
        "Policy Denial Rate — Medium Severity Threshold",
        "Denial rate at or above this value produces MEDIUM severity.",
        T.FLOAT,
        0.20,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_POLICY_DENIAL_SEVERITY_MEDIUM",
        runtime_applied=True,
        validator=range_validator(0.0, 1.0),
    ),
    _definition(
        "runtime_findings.policy_denial_rate.severity_low_threshold",
        C.AGENTS_RUNTIME,
        "Policy Denial Rate — Low Severity Threshold",
        "Denial rate at or above this value produces LOW severity.",
        T.FLOAT,
        0.10,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_POLICY_DENIAL_SEVERITY_LOW",
        runtime_applied=True,
        validator=range_validator(0.0, 1.0),
    ),
    _definition(
        "runtime_findings.policy_denial_rate.resolution_window_hours",
        C.AGENTS_RUNTIME,
        "Policy Denial Rate — Resolution Window (hours)",
        "Hours of normal metrics before auto-resolution.",
        T.INTEGER,
        48,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_POLICY_DENIAL_RESOLUTION_HOURS",
        runtime_applied=True,
        validator=range_validator(1, 720),
    ),

    # -----------------------------------------------------------------------
    # Repeated runtime error detector
    # -----------------------------------------------------------------------
    _definition(
        "runtime_findings.repeated_runtime_error.min_observation_count",
        C.AGENTS_RUNTIME,
        "Repeated Runtime Error — Min Observations",
        "Minimum error observations before the detector fires.",
        T.INTEGER,
        5,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_REPEATED_ERROR_MIN_OBSERVATIONS",
        runtime_applied=True,
        validator=range_validator(1, 10000),
    ),
    _definition(
        "runtime_findings.repeated_runtime_error.baseline_window_days",
        C.AGENTS_RUNTIME,
        "Repeated Runtime Error — Baseline Window (days)",
        "Number of days for the historical baseline window.",
        T.INTEGER,
        7,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_REPEATED_ERROR_BASELINE_DAYS",
        runtime_applied=True,
        validator=range_validator(1, 365),
    ),
    _definition(
        "runtime_findings.repeated_runtime_error.observation_window_hours",
        C.AGENTS_RUNTIME,
        "Repeated Runtime Error — Observation Window (hours)",
        "Number of hours for the current observation window.",
        T.INTEGER,
        24,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_REPEATED_ERROR_OBSERVATION_HOURS",
        runtime_applied=True,
        validator=range_validator(1, 720),
    ),
    _definition(
        "runtime_findings.repeated_runtime_error.absolute_threshold",
        C.AGENTS_RUNTIME,
        "Repeated Runtime Error — Absolute Threshold",
        "Minimum occurrences of the same error category to trigger.",
        T.INTEGER,
        3,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_REPEATED_ERROR_ABSOLUTE_THRESHOLD",
        runtime_applied=True,
        validator=range_validator(1, 1000),
    ),
    _definition(
        "runtime_findings.repeated_runtime_error.severity_critical_threshold",
        C.AGENTS_RUNTIME,
        "Repeated Runtime Error — Critical Severity Threshold",
        "Error count at or above this value produces CRITICAL severity.",
        T.INTEGER,
        20,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_REPEATED_ERROR_SEVERITY_CRITICAL",
        runtime_applied=True,
        validator=range_validator(1, 10000),
    ),
    _definition(
        "runtime_findings.repeated_runtime_error.severity_high_threshold",
        C.AGENTS_RUNTIME,
        "Repeated Runtime Error — High Severity Threshold",
        "Error count at or above this value produces HIGH severity.",
        T.INTEGER,
        10,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_REPEATED_ERROR_SEVERITY_HIGH",
        runtime_applied=True,
        validator=range_validator(1, 10000),
    ),
    _definition(
        "runtime_findings.repeated_runtime_error.severity_medium_threshold",
        C.AGENTS_RUNTIME,
        "Repeated Runtime Error — Medium Severity Threshold",
        "Error count at or above this value produces MEDIUM severity.",
        T.INTEGER,
        5,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_REPEATED_ERROR_SEVERITY_MEDIUM",
        runtime_applied=True,
        validator=range_validator(1, 10000),
    ),
    _definition(
        "runtime_findings.repeated_runtime_error.severity_low_threshold",
        C.AGENTS_RUNTIME,
        "Repeated Runtime Error — Low Severity Threshold",
        "Error count at or above this value produces LOW severity.",
        T.INTEGER,
        3,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_REPEATED_ERROR_SEVERITY_LOW",
        runtime_applied=True,
        validator=range_validator(1, 10000),
    ),
    _definition(
        "runtime_findings.repeated_runtime_error.resolution_window_hours",
        C.AGENTS_RUNTIME,
        "Repeated Runtime Error — Resolution Window (hours)",
        "Hours of normal metrics before auto-resolution.",
        T.INTEGER,
        24,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_REPEATED_ERROR_RESOLUTION_HOURS",
        runtime_applied=True,
        validator=range_validator(1, 720),
    ),

    # -----------------------------------------------------------------------
    # Auto-resolution behaviour (shared across all detectors)
    # -----------------------------------------------------------------------
    _definition(
        "runtime_findings.auto_resolution.consecutive_normal_windows",
        C.AGENTS_RUNTIME,
        "Auto-Resolution — Consecutive Normal Windows",
        "Number of consecutive observation windows with normal metrics "
        "before auto-resolving an active finding. Prevents oscillation: "
        "a single good window does not resolve a finding.",
        T.INTEGER,
        2,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_AUTO_RESOLUTION_CONSECUTIVE_WINDOWS",
        runtime_applied=True,
        validator=range_validator(1, 10),
    ),
    _definition(
        "runtime_findings.reconciliation.allowed_lateness_hours",
        C.AGENTS_RUNTIME,
        "Runtime Findings — Evidence Lateness Allowance (hours)",
        "Delay before a closed Runtime Findings observation window becomes final for reconciliation.",
        T.INTEGER,
        2,
        env="AI_GOVERNANCE_RUNTIME_FINDINGS_ALLOWED_LATENESS_HOURS",
        runtime_applied=True,
        validator=range_validator(0, 168),
    ),
    # -----------------------------------------------------------------------
    # Explicit local/test validation profile
    # -----------------------------------------------------------------------
    _definition(
        "runtime_findings.validation_profile.enabled",
        C.AGENTS_RUNTIME,
        "Runtime Findings — Local Validation Profile",
        "Enables minute-scale evidence windows only when the worker has also "
        "explicitly authorized this project for local validation.",
        T.BOOLEAN,
        False,
        runtime_applied=True,
        scopes=(SettingScope.PROJECT,),
    ),
    _definition(
        "runtime_findings.validation_profile.baseline_minutes",
        C.AGENTS_RUNTIME,
        "Runtime Findings — Validation Baseline (minutes)",
        "Historical baseline span for the explicitly enabled local validation profile.",
        T.INTEGER,
        10,
        runtime_applied=True,
        validator=range_validator(1, 1440),
        scopes=(SettingScope.PROJECT,),
    ),
    _definition(
        "runtime_findings.validation_profile.observation_minutes",
        C.AGENTS_RUNTIME,
        "Runtime Findings — Validation Observation (minutes)",
        "Observed evidence span for the explicitly enabled local validation profile.",
        T.INTEGER,
        2,
        runtime_applied=True,
        validator=range_validator(1, 1440),
        scopes=(SettingScope.PROJECT,),
    ),
    _definition(
        "runtime_findings.validation_profile.resolution_minutes",
        C.AGENTS_RUNTIME,
        "Runtime Findings — Validation Resolution Cadence (minutes)",
        "Completed-window cadence for the explicitly enabled local validation profile.",
        T.INTEGER,
        2,
        runtime_applied=True,
        validator=range_validator(1, 1440),
        scopes=(SettingScope.PROJECT,),
    ),
)
