#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT_DIR"
set -a
. "$ROOT_DIR/keycloak-postgres/.env.keycloak"
set +a

KC_URL="${KEYCLOAK_URL:-http://keycloak.localhost:8080}"
KC_ADMIN_USER="${KEYCLOAK_ADMIN_USERNAME:?KEYCLOAK_ADMIN_USERNAME is required}"
KC_ADMIN_PASSWORD="${KEYCLOAK_ADMIN_PASSWORD:?KEYCLOAK_ADMIN_PASSWORD is required}"
GENERATED_ENV="$ROOT_DIR/.env.service-accounts.generated"
OAUTH_ENV="$ROOT_DIR/.env.oauth.generated"

echo "[service-identities] Requesting Keycloak admin token..."
ADMIN_TOKEN=$(curl -sS -X POST \
  "$KC_URL/realms/master/protocol/openid-connect/token" \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  --data-urlencode grant_type=password \
  --data-urlencode client_id=admin-cli \
  --data-urlencode username="$KC_ADMIN_USER" \
  --data-urlencode password="$KC_ADMIN_PASSWORD" |
  jq -er '.access_token')

resolve_actor_id() {
  local client_id="$1"
  local client_uuid actor_id
  client_uuid=$(curl -sS \
    "$KC_URL/admin/realms/kavach/clients?clientId=$client_id" \
    -H "Authorization: Bearer $ADMIN_TOKEN" | jq -er '.[0].id')
  actor_id=$(curl -sS \
    "$KC_URL/admin/realms/kavach/clients/$client_uuid/service-account-user" \
    -H "Authorization: Bearer $ADMIN_TOKEN" | jq -er '.id')
  if [ -z "$actor_id" ] || [ "$actor_id" = "null" ]; then
    echo "[service-identities] Could not resolve $client_id service-account subject." >&2
    exit 1
  fi
  printf '%s' "$actor_id"
}

echo "[service-identities] Resolving Kavach service-account subjects..."
MCP_ACTOR_ID=$(resolve_actor_id kavach-mcp)
WALKTHROUGH_ACTOR_ID=$(resolve_actor_id kavach-walkthrough)

umask 077
cat > "$GENERATED_ENV" <<EOF
# Generated by scripts/keycloak/get-service-account-actorids.sh. Do not edit.
KAVACH_MCP_ACTOR_ID=$MCP_ACTOR_ID
KAVACH_WALKTHROUGH_ACTOR_ID=$WALKTHROUGH_ACTOR_ID
EOF

cat > "$OAUTH_ENV" <<EOF
# Generated by scripts/keycloak/get-service-account-actorids.sh. Do not edit.
KAVACH_OAUTH_TOKEN_URL=$KC_URL/realms/kavach/protocol/openid-connect/token
KAVACH_OAUTH_CLIENT_ID=kavach-walkthrough
KAVACH_OAUTH_CLIENT_SECRET=${KAVACH_WALKTHROUGH_CLIENT_SECRET:-walkthrough-secret}
EOF

echo "[service-identities] Wrote runtime configuration to $GENERATED_ENV"
echo "[service-identities] Wrote local OAuth configuration to $OAUTH_ENV"
