import os

from dotenv import load_dotenv  # type: ignore

load_dotenv()

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
OPENAI_DEFAULT_JUDGE_MODEL = os.getenv("OPENAI_DEFAULT_JUDGE_MODEL")

AI_GOVERNANCE_RUN_NEO4J_TESTS = os.getenv("AI_GOVERNANCE_RUN_NEO4J_TESTS", "false")
AI_GOVERNANCE_GRAPH_URI = os.getenv("AI_GOVERNANCE_GRAPH_URI", "bolt://localhost:7687")
AI_GOVERNANCE_GRAPH_USER = os.getenv("AI_GOVERNANCE_GRAPH_USER", "neo4j")
AI_GOVERNANCE_GRAPH_PASSWORD = os.getenv(
    "AI_GOVERNANCE_GRAPH_PASSWORD",
    "ai-governance-local-password",
)
AI_GOVERNANCE_GRAPH_DATABASE = os.getenv("AI_GOVERNANCE_GRAPH_DATABASE", "neo4j")

AI_GOVERNANCE_POLICY_REPOSITORY = os.getenv("AI_GOVERNANCE_POLICY_REPOSITORY", "inmemory").lower()
AI_GOVERNANCE_POLICY_SQLITE_PATH = os.getenv("AI_GOVERNANCE_POLICY_SQLITE_PATH")
AI_GOVERNANCE_POLICY_POSTGRES_DSN = os.getenv("AI_GOVERNANCE_POLICY_POSTGRES_DSN")
